version: "3"

services:
  app:
    build: 
      context: .
      args:
        DEV: "true"
    ports:
      - "8080:8080"
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - ./app:/ctbu/{{cookiecutter.project_slug}}/app/
      - ./ml/model/:/ctbu/{{cookiecutter.project_slug}}/ml/model/